language: node_js
os: osx
node_js:
  - "10"
before_script:
  - make tests/node_modules
script: 
  - mkdir championship
  - env EXPORT_CHAMPIONSHIP=$(pwd)/championship make test
deploy:
  provider: pages
  local_dir: championship
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: championship
  committer_from_gh: true
  on:
    branch: master
